OBJS=main.o ../shared/Logger.o ../shared/locationshm.o SerialHandler.o ../shared/strutils.o ../shared/config.o SocketHandler.o ATLocHandler.o
LIBS=-lpthread
BIN=celluploader.bin

CFLAGS+=-std=c99
CXXFLAGS+=-fpermissive -std=c++11

include ../Makefile.include

