OBJS=main.o SerialHandler.o ../shared/Logger.o ../shared/strutils.o NmeaParser.o nmea/GprmcMessage.o nmea/GpggaMessage.o NtpUpdater.o
BIN=gpslogger.bin

CFLAGS+=-std=c99
CXXFLAGS+=-fpermissive -std=c++11

include ../Makefile.include

